version: "3.9"
services:
        server:
                build: backend
                ports:
                        - 8000:8000
        web:
                build: intersection-viz
                ports:
                        - 5178:5178

